// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"hotel-booking-api/internal/room/model"
)

// NewMockRoomService creates a new instance of MockRoomService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoomService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoomService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRoomService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRoomService is an autogenerated mock type for the roomService type
type MockRoomService struct {
	mock.Mock
}

type MockRoomService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoomService) EXPECT() *MockRoomService_Expecter {
	return &MockRoomService_Expecter{mock: &_m.Mock}
}

// FindAllAvailableRooms provides a mock function for the type MockRoomService
func (_mock *MockRoomService) FindAllAvailableRooms(ctx context.Context, p model.FindAvailableRoomsParams) (*model.RoomsPage, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for FindAllAvailableRooms")
	}

	var r0 *model.RoomsPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.FindAvailableRoomsParams) (*model.RoomsPage, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.FindAvailableRoomsParams) *model.RoomsPage); ok {
		r0 = returnFunc(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RoomsPage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.FindAvailableRoomsParams) error); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoomService_FindAllAvailableRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllAvailableRooms'
type MockRoomService_FindAllAvailableRooms_Call struct {
	*mock.Call
}

// FindAllAvailableRooms is a helper method to define mock.On call
//   - ctx context.Context
//   - p model.FindAvailableRoomsParams
func (_e *MockRoomService_Expecter) FindAllAvailableRooms(ctx any, p any) *MockRoomService_FindAllAvailableRooms_Call {
	return &MockRoomService_FindAllAvailableRooms_Call{Call: _e.mock.On("FindAllAvailableRooms", ctx, p)}
}

func (_c *MockRoomService_FindAllAvailableRooms_Call) Run(run func(ctx context.Context, p model.FindAvailableRoomsParams)) *MockRoomService_FindAllAvailableRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.FindAvailableRoomsParams
		if args[1] != nil {
			arg1 = args[1].(model.FindAvailableRoomsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoomService_FindAllAvailableRooms_Call) Return(roomsPage *model.RoomsPage, err error) *MockRoomService_FindAllAvailableRooms_Call {
	_c.Call.Return(roomsPage, err)
	return _c
}

func (_c *MockRoomService_FindAllAvailableRooms_Call) RunAndReturn(run func(ctx context.Context, p model.FindAvailableRoomsParams) (*model.RoomsPage, error)) *MockRoomService_FindAllAvailableRooms_Call {
	_c.Call.Return(run)
	return _c
}
