// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"hotel-booking-api/internal/app/testing/model"
)

// NewMockTestingService creates a new instance of MockTestingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTestingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTestingService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockTestingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockTestingService is an autogenerated mock type for the testingService type
type MockTestingService struct {
	mock.Mock
}

type MockTestingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTestingService) EXPECT() *MockTestingService_Expecter {
	return &MockTestingService_Expecter{mock: &_m.Mock}
}

// ResetTestData provides a mock function for the type MockTestingService
func (_mock *MockTestingService) ResetTestData(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ResetTestData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTestingService_ResetTestData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetTestData'
type MockTestingService_ResetTestData_Call struct {
	*mock.Call
}

// ResetTestData is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTestingService_Expecter) ResetTestData(ctx any) *MockTestingService_ResetTestData_Call {
	return &MockTestingService_ResetTestData_Call{Call: _e.mock.On("ResetTestData", ctx)}
}

func (_c *MockTestingService_ResetTestData_Call) Run(run func(ctx context.Context)) *MockTestingService_ResetTestData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTestingService_ResetTestData_Call) Return(err error) *MockTestingService_ResetTestData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTestingService_ResetTestData_Call) RunAndReturn(run func(ctx context.Context) error) *MockTestingService_ResetTestData_Call {
	_c.Call.Return(run)
	return _c
}

// SeedTestData provides a mock function for the type MockTestingService
func (_mock *MockTestingService) SeedTestData(ctx context.Context, p model.SeedParams) (*model.SeedResult, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for SeedTestData")
	}

	var r0 *model.SeedResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.SeedParams) (*model.SeedResult, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.SeedParams) *model.SeedResult); ok {
		r0 = returnFunc(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SeedResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.SeedParams) error); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTestingService_SeedTestData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SeedTestData'
type MockTestingService_SeedTestData_Call struct {
	*mock.Call
}

// SeedTestData is a helper method to define mock.On call
//   - ctx context.Context
//   - p model.SeedParams
func (_e *MockTestingService_Expecter) SeedTestData(ctx any, p any) *MockTestingService_SeedTestData_Call {
	return &MockTestingService_SeedTestData_Call{Call: _e.mock.On("SeedTestData", ctx, p)}
}

func (_c *MockTestingService_SeedTestData_Call) Run(run func(ctx context.Context, p model.SeedParams)) *MockTestingService_SeedTestData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.SeedParams
		if args[1] != nil {
			arg1 = args[1].(model.SeedParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTestingService_SeedTestData_Call) Return(seedResult *model.SeedResult, err error) *MockTestingService_SeedTestData_Call {
	_c.Call.Return(seedResult, err)
	return _c
}

func (_c *MockTestingService_SeedTestData_Call) RunAndReturn(run func(ctx context.Context, p model.SeedParams) (*model.SeedResult, error)) *MockTestingService_SeedTestData_Call {
	_c.Call.Return(run)
	return _c
}
