// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"hotel-booking-api/internal/hotel/model"
)

// NewMockHotelService creates a new instance of MockHotelService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHotelService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHotelService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockHotelService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockHotelService is an autogenerated mock type for the hotelService type
type MockHotelService struct {
	mock.Mock
}

type MockHotelService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHotelService) EXPECT() *MockHotelService_Expecter {
	return &MockHotelService_Expecter{mock: &_m.Mock}
}

// FindAllHotels provides a mock function for the type MockHotelService
func (_mock *MockHotelService) FindAllHotels(ctx context.Context, p model.FindHotelsParams) (*model.HotelsPage, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for FindAllHotels")
	}

	var r0 *model.HotelsPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.FindHotelsParams) (*model.HotelsPage, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.FindHotelsParams) *model.HotelsPage); ok {
		r0 = returnFunc(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.HotelsPage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.FindHotelsParams) error); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHotelService_FindAllHotels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllHotels'
type MockHotelService_FindAllHotels_Call struct {
	*mock.Call
}

// FindAllHotels is a helper method to define mock.On call
//   - ctx context.Context
//   - p model.FindHotelsParams
func (_e *MockHotelService_Expecter) FindAllHotels(ctx any, p any) *MockHotelService_FindAllHotels_Call {
	return &MockHotelService_FindAllHotels_Call{Call: _e.mock.On("FindAllHotels", ctx, p)}
}

func (_c *MockHotelService_FindAllHotels_Call) Run(run func(ctx context.Context, p model.FindHotelsParams)) *MockHotelService_FindAllHotels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.FindHotelsParams
		if args[1] != nil {
			arg1 = args[1].(model.FindHotelsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHotelService_FindAllHotels_Call) Return(hotelsPage *model.HotelsPage, err error) *MockHotelService_FindAllHotels_Call {
	_c.Call.Return(hotelsPage, err)
	return _c
}

func (_c *MockHotelService_FindAllHotels_Call) RunAndReturn(run func(ctx context.Context, p model.FindHotelsParams) (*model.HotelsPage, error)) *MockHotelService_FindAllHotels_Call {
	_c.Call.Return(run)
	return _c
}
