// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"hotel-booking-api/internal/reservation/model"
)

// NewMockReservationRepository creates a new instance of MockReservationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReservationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReservationRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockReservationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockReservationRepository is an autogenerated mock type for the reservationRepository type
type MockReservationRepository struct {
	mock.Mock
}

type MockReservationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReservationRepository) EXPECT() *MockReservationRepository_Expecter {
	return &MockReservationRepository_Expecter{mock: &_m.Mock}
}

// DeleteAllReservations provides a mock function for the type MockReservationRepository
func (_mock *MockReservationRepository) DeleteAllReservations(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllReservations")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReservationRepository_DeleteAllReservations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllReservations'
type MockReservationRepository_DeleteAllReservations_Call struct {
	*mock.Call
}

// DeleteAllReservations is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReservationRepository_Expecter) DeleteAllReservations(ctx any) *MockReservationRepository_DeleteAllReservations_Call {
	return &MockReservationRepository_DeleteAllReservations_Call{Call: _e.mock.On("DeleteAllReservations", ctx)}
}

func (_c *MockReservationRepository_DeleteAllReservations_Call) Run(run func(ctx context.Context)) *MockReservationRepository_DeleteAllReservations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReservationRepository_DeleteAllReservations_Call) Return(err error) *MockReservationRepository_DeleteAllReservations_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReservationRepository_DeleteAllReservations_Call) RunAndReturn(run func(ctx context.Context) error) *MockReservationRepository_DeleteAllReservations_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllReservationsByStatus provides a mock function for the type MockReservationRepository
func (_mock *MockReservationRepository) GetAllReservationsByStatus(ctx context.Context, status model.ReservationStatus) ([]*model.ReservationItem, error) {
	ret := _mock.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for GetAllReservationsByStatus")
	}

	var r0 []*model.ReservationItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ReservationStatus) ([]*model.ReservationItem, error)); ok {
		return returnFunc(ctx, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ReservationStatus) []*model.ReservationItem); ok {
		r0 = returnFunc(ctx, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.ReservationItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.ReservationStatus) error); ok {
		r1 = returnFunc(ctx, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservationRepository_GetAllReservationsByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllReservationsByStatus'
type MockReservationRepository_GetAllReservationsByStatus_Call struct {
	*mock.Call
}

// GetAllReservationsByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status model.ReservationStatus
func (_e *MockReservationRepository_Expecter) GetAllReservationsByStatus(ctx any, status any) *MockReservationRepository_GetAllReservationsByStatus_Call {
	return &MockReservationRepository_GetAllReservationsByStatus_Call{Call: _e.mock.On("GetAllReservationsByStatus", ctx, status)}
}

func (_c *MockReservationRepository_GetAllReservationsByStatus_Call) Run(run func(ctx context.Context, status model.ReservationStatus)) *MockReservationRepository_GetAllReservationsByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.ReservationStatus
		if args[1] != nil {
			arg1 = args[1].(model.ReservationStatus)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReservationRepository_GetAllReservationsByStatus_Call) Return(reservationItems []*model.ReservationItem, err error) *MockReservationRepository_GetAllReservationsByStatus_Call {
	_c.Call.Return(reservationItems, err)
	return _c
}

func (_c *MockReservationRepository_GetAllReservationsByStatus_Call) RunAndReturn(run func(ctx context.Context, status model.ReservationStatus) ([]*model.ReservationItem, error)) *MockReservationRepository_GetAllReservationsByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetReservationByID provides a mock function for the type MockReservationRepository
func (_mock *MockReservationRepository) GetReservationByID(ctx context.Context, reservationID string) (*model.ReservationItem, error) {
	ret := _mock.Called(ctx, reservationID)

	if len(ret) == 0 {
		panic("no return value specified for GetReservationByID")
	}

	var r0 *model.ReservationItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.ReservationItem, error)); ok {
		return returnFunc(ctx, reservationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.ReservationItem); ok {
		r0 = returnFunc(ctx, reservationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ReservationItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, reservationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservationRepository_GetReservationByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReservationByID'
type MockReservationRepository_GetReservationByID_Call struct {
	*mock.Call
}

// GetReservationByID is a helper method to define mock.On call
//   - ctx context.Context
//   - reservationID string
func (_e *MockReservationRepository_Expecter) GetReservationByID(ctx any, reservationID any) *MockReservationRepository_GetReservationByID_Call {
	return &MockReservationRepository_GetReservationByID_Call{Call: _e.mock.On("GetReservationByID", ctx, reservationID)}
}

func (_c *MockReservationRepository_GetReservationByID_Call) Run(run func(ctx context.Context, reservationID string)) *MockReservationRepository_GetReservationByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReservationRepository_GetReservationByID_Call) Return(reservationItem *model.ReservationItem, err error) *MockReservationRepository_GetReservationByID_Call {
	_c.Call.Return(reservationItem, err)
	return _c
}

func (_c *MockReservationRepository_GetReservationByID_Call) RunAndReturn(run func(ctx context.Context, reservationID string) (*model.ReservationItem, error)) *MockReservationRepository_GetReservationByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetReservationByReference provides a mock function for the type MockReservationRepository
func (_mock *MockReservationRepository) GetReservationByReference(ctx context.Context, bookingRef string) (*model.ReservationItem, error) {
	ret := _mock.Called(ctx, bookingRef)

	if len(ret) == 0 {
		panic("no return value specified for GetReservationByReference")
	}

	var r0 *model.ReservationItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.ReservationItem, error)); ok {
		return returnFunc(ctx, bookingRef)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.ReservationItem); ok {
		r0 = returnFunc(ctx, bookingRef)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ReservationItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, bookingRef)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservationRepository_GetReservationByReference_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReservationByReference'
type MockReservationRepository_GetReservationByReference_Call struct {
	*mock.Call
}

// GetReservationByReference is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingRef string
func (_e *MockReservationRepository_Expecter) GetReservationByReference(ctx any, bookingRef any) *MockReservationRepository_GetReservationByReference_Call {
	return &MockReservationRepository_GetReservationByReference_Call{Call: _e.mock.On("GetReservationByReference", ctx, bookingRef)}
}

func (_c *MockReservationRepository_GetReservationByReference_Call) Run(run func(ctx context.Context, bookingRef string)) *MockReservationRepository_GetReservationByReference_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReservationRepository_GetReservationByReference_Call) Return(reservationItem *model.ReservationItem, err error) *MockReservationRepository_GetReservationByReference_Call {
	_c.Call.Return(reservationItem, err)
	return _c
}

func (_c *MockReservationRepository_GetReservationByReference_Call) RunAndReturn(run func(ctx context.Context, bookingRef string) (*model.ReservationItem, error)) *MockReservationRepository_GetReservationByReference_Call {
	_c.Call.Return(run)
	return _c
}

// PutReservation provides a mock function for the type MockReservationRepository
func (_mock *MockReservationRepository) PutReservation(ctx context.Context, r model.ReservationItem) (*model.ReservationItem, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for PutReservation")
	}

	var r0 *model.ReservationItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ReservationItem) (*model.ReservationItem, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ReservationItem) *model.ReservationItem); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ReservationItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.ReservationItem) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservationRepository_PutReservation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutReservation'
type MockReservationRepository_PutReservation_Call struct {
	*mock.Call
}

// PutReservation is a helper method to define mock.On call
//   - ctx context.Context
//   - r model.ReservationItem
func (_e *MockReservationRepository_Expecter) PutReservation(ctx any, r any) *MockReservationRepository_PutReservation_Call {
	return &MockReservationRepository_PutReservation_Call{Call: _e.mock.On("PutReservation", ctx, r)}
}

func (_c *MockReservationRepository_PutReservation_Call) Run(run func(ctx context.Context, r model.ReservationItem)) *MockReservationRepository_PutReservation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.ReservationItem
		if args[1] != nil {
			arg1 = args[1].(model.ReservationItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReservationRepository_PutReservation_Call) Return(reservationItem *model.ReservationItem, err error) *MockReservationRepository_PutReservation_Call {
	_c.Call.Return(reservationItem, err)
	return _c
}

func (_c *MockReservationRepository_PutReservation_Call) RunAndReturn(run func(ctx context.Context, r model.ReservationItem) (*model.ReservationItem, error)) *MockReservationRepository_PutReservation_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateReservationStatus provides a mock function for the type MockReservationRepository
func (_mock *MockReservationRepository) UpdateReservationStatus(ctx context.Context, reservationID string, status model.ReservationStatus) (*model.ReservationItem, error) {
	ret := _mock.Called(ctx, reservationID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReservationStatus")
	}

	var r0 *model.ReservationItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.ReservationStatus) (*model.ReservationItem, error)); ok {
		return returnFunc(ctx, reservationID, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.ReservationStatus) *model.ReservationItem); ok {
		r0 = returnFunc(ctx, reservationID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ReservationItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, model.ReservationStatus) error); ok {
		r1 = returnFunc(ctx, reservationID, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservationRepository_UpdateReservationStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateReservationStatus'
type MockReservationRepository_UpdateReservationStatus_Call struct {
	*mock.Call
}

// UpdateReservationStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - reservationID string
//   - status model.ReservationStatus
func (_e *MockReservationRepository_Expecter) UpdateReservationStatus(ctx any, reservationID any, status any) *MockReservationRepository_UpdateReservationStatus_Call {
	return &MockReservationRepository_UpdateReservationStatus_Call{Call: _e.mock.On("UpdateReservationStatus", ctx, reservationID, status)}
}

func (_c *MockReservationRepository_UpdateReservationStatus_Call) Run(run func(ctx context.Context, reservationID string, status model.ReservationStatus)) *MockReservationRepository_UpdateReservationStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.ReservationStatus
		if args[2] != nil {
			arg2 = args[2].(model.ReservationStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReservationRepository_UpdateReservationStatus_Call) Return(reservationItem *model.ReservationItem, err error) *MockReservationRepository_UpdateReservationStatus_Call {
	_c.Call.Return(reservationItem, err)
	return _c
}

func (_c *MockReservationRepository_UpdateReservationStatus_Call) RunAndReturn(run func(ctx context.Context, reservationID string, status model.ReservationStatus) (*model.ReservationItem, error)) *MockReservationRepository_UpdateReservationStatus_Call {
	_c.Call.Return(run)
	return _c
}
