// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"hotel-booking-api/internal/reservation/model"
)

// NewMockReservationService creates a new instance of MockReservationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReservationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReservationService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockReservationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockReservationService is an autogenerated mock type for the reservationService type
type MockReservationService struct {
	mock.Mock
}

type MockReservationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReservationService) EXPECT() *MockReservationService_Expecter {
	return &MockReservationService_Expecter{mock: &_m.Mock}
}

// CreateReservation provides a mock function for the type MockReservationService
func (_mock *MockReservationService) CreateReservation(ctx context.Context, r model.ReservationItem) (*model.ReservationItem, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for CreateReservation")
	}

	var r0 *model.ReservationItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ReservationItem) (*model.ReservationItem, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ReservationItem) *model.ReservationItem); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ReservationItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.ReservationItem) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservationService_CreateReservation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReservation'
type MockReservationService_CreateReservation_Call struct {
	*mock.Call
}

// CreateReservation is a helper method to define mock.On call
//   - ctx context.Context
//   - r model.ReservationItem
func (_e *MockReservationService_Expecter) CreateReservation(ctx any, r any) *MockReservationService_CreateReservation_Call {
	return &MockReservationService_CreateReservation_Call{Call: _e.mock.On("CreateReservation", ctx, r)}
}

func (_c *MockReservationService_CreateReservation_Call) Run(run func(ctx context.Context, r model.ReservationItem)) *MockReservationService_CreateReservation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.ReservationItem
		if args[1] != nil {
			arg1 = args[1].(model.ReservationItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReservationService_CreateReservation_Call) Return(reservationItem *model.ReservationItem, err error) *MockReservationService_CreateReservation_Call {
	_c.Call.Return(reservationItem, err)
	return _c
}

func (_c *MockReservationService_CreateReservation_Call) RunAndReturn(run func(ctx context.Context, r model.ReservationItem) (*model.ReservationItem, error)) *MockReservationService_CreateReservation_Call {
	_c.Call.Return(run)
	return _c
}

// FindReservationByReference provides a mock function for the type MockReservationService
func (_mock *MockReservationService) FindReservationByReference(ctx context.Context, bookingRef string) (*model.ReservationItem, error) {
	ret := _mock.Called(ctx, bookingRef)

	if len(ret) == 0 {
		panic("no return value specified for FindReservationByReference")
	}

	var r0 *model.ReservationItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.ReservationItem, error)); ok {
		return returnFunc(ctx, bookingRef)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.ReservationItem); ok {
		r0 = returnFunc(ctx, bookingRef)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ReservationItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, bookingRef)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservationService_FindReservationByReference_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindReservationByReference'
type MockReservationService_FindReservationByReference_Call struct {
	*mock.Call
}

// FindReservationByReference is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingRef string
func (_e *MockReservationService_Expecter) FindReservationByReference(ctx any, bookingRef any) *MockReservationService_FindReservationByReference_Call {
	return &MockReservationService_FindReservationByReference_Call{Call: _e.mock.On("FindReservationByReference", ctx, bookingRef)}
}

func (_c *MockReservationService_FindReservationByReference_Call) Run(run func(ctx context.Context, bookingRef string)) *MockReservationService_FindReservationByReference_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReservationService_FindReservationByReference_Call) Return(reservationItem *model.ReservationItem, err error) *MockReservationService_FindReservationByReference_Call {
	_c.Call.Return(reservationItem, err)
	return _c
}

func (_c *MockReservationService_FindReservationByReference_Call) RunAndReturn(run func(ctx context.Context, bookingRef string) (*model.ReservationItem, error)) *MockReservationService_FindReservationByReference_Call {
	_c.Call.Return(run)
	return _c
}
