// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"hotel-booking-api/internal/hotel/model"
)

// NewMockHotelRepository creates a new instance of MockHotelRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHotelRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHotelRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockHotelRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockHotelRepository is an autogenerated mock type for the hotelRepository type
type MockHotelRepository struct {
	mock.Mock
}

type MockHotelRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHotelRepository) EXPECT() *MockHotelRepository_Expecter {
	return &MockHotelRepository_Expecter{mock: &_m.Mock}
}

// DeleteAllHotels provides a mock function for the type MockHotelRepository
func (_mock *MockHotelRepository) DeleteAllHotels(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllHotels")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHotelRepository_DeleteAllHotels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllHotels'
type MockHotelRepository_DeleteAllHotels_Call struct {
	*mock.Call
}

// DeleteAllHotels is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHotelRepository_Expecter) DeleteAllHotels(ctx any) *MockHotelRepository_DeleteAllHotels_Call {
	return &MockHotelRepository_DeleteAllHotels_Call{Call: _e.mock.On("DeleteAllHotels", ctx)}
}

func (_c *MockHotelRepository_DeleteAllHotels_Call) Run(run func(ctx context.Context)) *MockHotelRepository_DeleteAllHotels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHotelRepository_DeleteAllHotels_Call) Return(err error) *MockHotelRepository_DeleteAllHotels_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHotelRepository_DeleteAllHotels_Call) RunAndReturn(run func(ctx context.Context) error) *MockHotelRepository_DeleteAllHotels_Call {
	_c.Call.Return(run)
	return _c
}

// GetHotelsByName provides a mock function for the type MockHotelRepository
func (_mock *MockHotelRepository) GetHotelsByName(ctx context.Context, p model.FindHotelsParams) (*model.HotelsPage, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for GetHotelsByName")
	}

	var r0 *model.HotelsPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.FindHotelsParams) (*model.HotelsPage, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.FindHotelsParams) *model.HotelsPage); ok {
		r0 = returnFunc(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.HotelsPage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.FindHotelsParams) error); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHotelRepository_GetHotelsByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHotelsByName'
type MockHotelRepository_GetHotelsByName_Call struct {
	*mock.Call
}

// GetHotelsByName is a helper method to define mock.On call
//   - ctx context.Context
//   - p model.FindHotelsParams
func (_e *MockHotelRepository_Expecter) GetHotelsByName(ctx any, p any) *MockHotelRepository_GetHotelsByName_Call {
	return &MockHotelRepository_GetHotelsByName_Call{Call: _e.mock.On("GetHotelsByName", ctx, p)}
}

func (_c *MockHotelRepository_GetHotelsByName_Call) Run(run func(ctx context.Context, p model.FindHotelsParams)) *MockHotelRepository_GetHotelsByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.FindHotelsParams
		if args[1] != nil {
			arg1 = args[1].(model.FindHotelsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHotelRepository_GetHotelsByName_Call) Return(hotelsPage *model.HotelsPage, err error) *MockHotelRepository_GetHotelsByName_Call {
	_c.Call.Return(hotelsPage, err)
	return _c
}

func (_c *MockHotelRepository_GetHotelsByName_Call) RunAndReturn(run func(ctx context.Context, p model.FindHotelsParams) (*model.HotelsPage, error)) *MockHotelRepository_GetHotelsByName_Call {
	_c.Call.Return(run)
	return _c
}

// PutHotels provides a mock function for the type MockHotelRepository
func (_mock *MockHotelRepository) PutHotels(ctx context.Context, hotels []*model.HotelItem) error {
	ret := _mock.Called(ctx, hotels)

	if len(ret) == 0 {
		panic("no return value specified for PutHotels")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*model.HotelItem) error); ok {
		r0 = returnFunc(ctx, hotels)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHotelRepository_PutHotels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutHotels'
type MockHotelRepository_PutHotels_Call struct {
	*mock.Call
}

// PutHotels is a helper method to define mock.On call
//   - ctx context.Context
//   - hotels []*model.HotelItem
func (_e *MockHotelRepository_Expecter) PutHotels(ctx any, hotels any) *MockHotelRepository_PutHotels_Call {
	return &MockHotelRepository_PutHotels_Call{Call: _e.mock.On("PutHotels", ctx, hotels)}
}

func (_c *MockHotelRepository_PutHotels_Call) Run(run func(ctx context.Context, hotels []*model.HotelItem)) *MockHotelRepository_PutHotels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*model.HotelItem
		if args[1] != nil {
			arg1 = args[1].([]*model.HotelItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHotelRepository_PutHotels_Call) Return(err error) *MockHotelRepository_PutHotels_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHotelRepository_PutHotels_Call) RunAndReturn(run func(ctx context.Context, hotels []*model.HotelItem) error) *MockHotelRepository_PutHotels_Call {
	_c.Call.Return(run)
	return _c
}
