// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"hotel-booking-api/internal/room/model"
)

// NewMockRoomRepository creates a new instance of MockRoomRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoomRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoomRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRoomRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRoomRepository is an autogenerated mock type for the roomRepository type
type MockRoomRepository struct {
	mock.Mock
}

type MockRoomRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoomRepository) EXPECT() *MockRoomRepository_Expecter {
	return &MockRoomRepository_Expecter{mock: &_m.Mock}
}

// DeleteAllRooms provides a mock function for the type MockRoomRepository
func (_mock *MockRoomRepository) DeleteAllRooms(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllRooms")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRoomRepository_DeleteAllRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllRooms'
type MockRoomRepository_DeleteAllRooms_Call struct {
	*mock.Call
}

// DeleteAllRooms is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoomRepository_Expecter) DeleteAllRooms(ctx any) *MockRoomRepository_DeleteAllRooms_Call {
	return &MockRoomRepository_DeleteAllRooms_Call{Call: _e.mock.On("DeleteAllRooms", ctx)}
}

func (_c *MockRoomRepository_DeleteAllRooms_Call) Run(run func(ctx context.Context)) *MockRoomRepository_DeleteAllRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRoomRepository_DeleteAllRooms_Call) Return(err error) *MockRoomRepository_DeleteAllRooms_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRoomRepository_DeleteAllRooms_Call) RunAndReturn(run func(ctx context.Context) error) *MockRoomRepository_DeleteAllRooms_Call {
	_c.Call.Return(run)
	return _c
}

// GetAvailableRooms provides a mock function for the type MockRoomRepository
func (_mock *MockRoomRepository) GetAvailableRooms(ctx context.Context, p model.FindAvailableRoomsParams) (*model.RoomsPage, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableRooms")
	}

	var r0 *model.RoomsPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.FindAvailableRoomsParams) (*model.RoomsPage, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.FindAvailableRoomsParams) *model.RoomsPage); ok {
		r0 = returnFunc(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RoomsPage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.FindAvailableRoomsParams) error); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoomRepository_GetAvailableRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvailableRooms'
type MockRoomRepository_GetAvailableRooms_Call struct {
	*mock.Call
}

// GetAvailableRooms is a helper method to define mock.On call
//   - ctx context.Context
//   - p model.FindAvailableRoomsParams
func (_e *MockRoomRepository_Expecter) GetAvailableRooms(ctx any, p any) *MockRoomRepository_GetAvailableRooms_Call {
	return &MockRoomRepository_GetAvailableRooms_Call{Call: _e.mock.On("GetAvailableRooms", ctx, p)}
}

func (_c *MockRoomRepository_GetAvailableRooms_Call) Run(run func(ctx context.Context, p model.FindAvailableRoomsParams)) *MockRoomRepository_GetAvailableRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.FindAvailableRoomsParams
		if args[1] != nil {
			arg1 = args[1].(model.FindAvailableRoomsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoomRepository_GetAvailableRooms_Call) Return(roomsPage *model.RoomsPage, err error) *MockRoomRepository_GetAvailableRooms_Call {
	_c.Call.Return(roomsPage, err)
	return _c
}

func (_c *MockRoomRepository_GetAvailableRooms_Call) RunAndReturn(run func(ctx context.Context, p model.FindAvailableRoomsParams) (*model.RoomsPage, error)) *MockRoomRepository_GetAvailableRooms_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoomTypes provides a mock function for the type MockRoomRepository
func (_mock *MockRoomRepository) GetRoomTypes(ctx context.Context) ([]*model.RoomType, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRoomTypes")
	}

	var r0 []*model.RoomType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*model.RoomType, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*model.RoomType); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.RoomType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoomRepository_GetRoomTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoomTypes'
type MockRoomRepository_GetRoomTypes_Call struct {
	*mock.Call
}

// GetRoomTypes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoomRepository_Expecter) GetRoomTypes(ctx any) *MockRoomRepository_GetRoomTypes_Call {
	return &MockRoomRepository_GetRoomTypes_Call{Call: _e.mock.On("GetRoomTypes", ctx)}
}

func (_c *MockRoomRepository_GetRoomTypes_Call) Run(run func(ctx context.Context)) *MockRoomRepository_GetRoomTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRoomRepository_GetRoomTypes_Call) Return(roomTypes []*model.RoomType, err error) *MockRoomRepository_GetRoomTypes_Call {
	_c.Call.Return(roomTypes, err)
	return _c
}

func (_c *MockRoomRepository_GetRoomTypes_Call) RunAndReturn(run func(ctx context.Context) ([]*model.RoomType, error)) *MockRoomRepository_GetRoomTypes_Call {
	_c.Call.Return(run)
	return _c
}

// PutRooms provides a mock function for the type MockRoomRepository
func (_mock *MockRoomRepository) PutRooms(ctx context.Context, rooms []*model.RoomItem) error {
	ret := _mock.Called(ctx, rooms)

	if len(ret) == 0 {
		panic("no return value specified for PutRooms")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*model.RoomItem) error); ok {
		r0 = returnFunc(ctx, rooms)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRoomRepository_PutRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutRooms'
type MockRoomRepository_PutRooms_Call struct {
	*mock.Call
}

// PutRooms is a helper method to define mock.On call
//   - ctx context.Context
//   - rooms []*model.RoomItem
func (_e *MockRoomRepository_Expecter) PutRooms(ctx any, rooms any) *MockRoomRepository_PutRooms_Call {
	return &MockRoomRepository_PutRooms_Call{Call: _e.mock.On("PutRooms", ctx, rooms)}
}

func (_c *MockRoomRepository_PutRooms_Call) Run(run func(ctx context.Context, rooms []*model.RoomItem)) *MockRoomRepository_PutRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*model.RoomItem
		if args[1] != nil {
			arg1 = args[1].([]*model.RoomItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoomRepository_PutRooms_Call) Return(err error) *MockRoomRepository_PutRooms_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRoomRepository_PutRooms_Call) RunAndReturn(run func(ctx context.Context, rooms []*model.RoomItem) error) *MockRoomRepository_PutRooms_Call {
	_c.Call.Return(run)
	return _c
}
