// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"hotel-booking-api/internal/reservation/model"
)

// NewMockReservationService creates a new instance of MockReservationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReservationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReservationService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockReservationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockReservationService is an autogenerated mock type for the reservationService type
type MockReservationService struct {
	mock.Mock
}

type MockReservationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReservationService) EXPECT() *MockReservationService_Expecter {
	return &MockReservationService_Expecter{mock: &_m.Mock}
}

// ConfirmReservation provides a mock function for the type MockReservationService
func (_mock *MockReservationService) ConfirmReservation(ctx context.Context, reservationID string) (*model.ReservationItem, error) {
	ret := _mock.Called(ctx, reservationID)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmReservation")
	}

	var r0 *model.ReservationItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.ReservationItem, error)); ok {
		return returnFunc(ctx, reservationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.ReservationItem); ok {
		r0 = returnFunc(ctx, reservationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ReservationItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, reservationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservationService_ConfirmReservation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmReservation'
type MockReservationService_ConfirmReservation_Call struct {
	*mock.Call
}

// ConfirmReservation is a helper method to define mock.On call
//   - ctx context.Context
//   - reservationID string
func (_e *MockReservationService_Expecter) ConfirmReservation(ctx any, reservationID any) *MockReservationService_ConfirmReservation_Call {
	return &MockReservationService_ConfirmReservation_Call{Call: _e.mock.On("ConfirmReservation", ctx, reservationID)}
}

func (_c *MockReservationService_ConfirmReservation_Call) Run(run func(ctx context.Context, reservationID string)) *MockReservationService_ConfirmReservation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReservationService_ConfirmReservation_Call) Return(reservationItem *model.ReservationItem, err error) *MockReservationService_ConfirmReservation_Call {
	_c.Call.Return(reservationItem, err)
	return _c
}

func (_c *MockReservationService_ConfirmReservation_Call) RunAndReturn(run func(ctx context.Context, reservationID string) (*model.ReservationItem, error)) *MockReservationService_ConfirmReservation_Call {
	_c.Call.Return(run)
	return _c
}

// FindReservationByStatus provides a mock function for the type MockReservationService
func (_mock *MockReservationService) FindReservationByStatus(ctx context.Context, status model.ReservationStatus) ([]*model.ReservationItem, error) {
	ret := _mock.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for FindReservationByStatus")
	}

	var r0 []*model.ReservationItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ReservationStatus) ([]*model.ReservationItem, error)); ok {
		return returnFunc(ctx, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ReservationStatus) []*model.ReservationItem); ok {
		r0 = returnFunc(ctx, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.ReservationItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.ReservationStatus) error); ok {
		r1 = returnFunc(ctx, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservationService_FindReservationByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindReservationByStatus'
type MockReservationService_FindReservationByStatus_Call struct {
	*mock.Call
}

// FindReservationByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status model.ReservationStatus
func (_e *MockReservationService_Expecter) FindReservationByStatus(ctx any, status any) *MockReservationService_FindReservationByStatus_Call {
	return &MockReservationService_FindReservationByStatus_Call{Call: _e.mock.On("FindReservationByStatus", ctx, status)}
}

func (_c *MockReservationService_FindReservationByStatus_Call) Run(run func(ctx context.Context, status model.ReservationStatus)) *MockReservationService_FindReservationByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.ReservationStatus
		if args[1] != nil {
			arg1 = args[1].(model.ReservationStatus)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReservationService_FindReservationByStatus_Call) Return(reservationItems []*model.ReservationItem, err error) *MockReservationService_FindReservationByStatus_Call {
	_c.Call.Return(reservationItems, err)
	return _c
}

func (_c *MockReservationService_FindReservationByStatus_Call) RunAndReturn(run func(ctx context.Context, status model.ReservationStatus) ([]*model.ReservationItem, error)) *MockReservationService_FindReservationByStatus_Call {
	_c.Call.Return(run)
	return _c
}
