// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	"database/sql"

	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHotelHandler creates a new instance of MockHotelHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHotelHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHotelHandler {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockHotelHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockHotelHandler is an autogenerated mock type for the hotelHandler type
type MockHotelHandler struct {
	mock.Mock
}

type MockHotelHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHotelHandler) EXPECT() *MockHotelHandler_Expecter {
	return &MockHotelHandler_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function for the type MockHotelHandler
func (_mock *MockHotelHandler) GetAll(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockHotelHandler_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockHotelHandler_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockHotelHandler_Expecter) GetAll(c any) *MockHotelHandler_GetAll_Call {
	return &MockHotelHandler_GetAll_Call{Call: _e.mock.On("GetAll", c)}
}

func (_c *MockHotelHandler_GetAll_Call) Run(run func(c *gin.Context)) *MockHotelHandler_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHotelHandler_GetAll_Call) Return() *MockHotelHandler_GetAll_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHotelHandler_GetAll_Call) RunAndReturn(run func(c *gin.Context)) *MockHotelHandler_GetAll_Call {
	_c.Run(run)
	return _c
}

// NewMockRoomHandler creates a new instance of MockRoomHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoomHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoomHandler {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRoomHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRoomHandler is an autogenerated mock type for the roomHandler type
type MockRoomHandler struct {
	mock.Mock
}

type MockRoomHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoomHandler) EXPECT() *MockRoomHandler_Expecter {
	return &MockRoomHandler_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function for the type MockRoomHandler
func (_mock *MockRoomHandler) GetAll(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockRoomHandler_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockRoomHandler_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockRoomHandler_Expecter) GetAll(c any) *MockRoomHandler_GetAll_Call {
	return &MockRoomHandler_GetAll_Call{Call: _e.mock.On("GetAll", c)}
}

func (_c *MockRoomHandler_GetAll_Call) Run(run func(c *gin.Context)) *MockRoomHandler_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRoomHandler_GetAll_Call) Return() *MockRoomHandler_GetAll_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRoomHandler_GetAll_Call) RunAndReturn(run func(c *gin.Context)) *MockRoomHandler_GetAll_Call {
	_c.Run(run)
	return _c
}

// NewMockReservationHandler creates a new instance of MockReservationHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReservationHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReservationHandler {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockReservationHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockReservationHandler is an autogenerated mock type for the reservationHandler type
type MockReservationHandler struct {
	mock.Mock
}

type MockReservationHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReservationHandler) EXPECT() *MockReservationHandler_Expecter {
	return &MockReservationHandler_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockReservationHandler
func (_mock *MockReservationHandler) Create(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockReservationHandler_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockReservationHandler_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockReservationHandler_Expecter) Create(c any) *MockReservationHandler_Create_Call {
	return &MockReservationHandler_Create_Call{Call: _e.mock.On("Create", c)}
}

func (_c *MockReservationHandler_Create_Call) Run(run func(c *gin.Context)) *MockReservationHandler_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReservationHandler_Create_Call) Return() *MockReservationHandler_Create_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReservationHandler_Create_Call) RunAndReturn(run func(c *gin.Context)) *MockReservationHandler_Create_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type MockReservationHandler
func (_mock *MockReservationHandler) Get(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockReservationHandler_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockReservationHandler_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockReservationHandler_Expecter) Get(c any) *MockReservationHandler_Get_Call {
	return &MockReservationHandler_Get_Call{Call: _e.mock.On("Get", c)}
}

func (_c *MockReservationHandler_Get_Call) Run(run func(c *gin.Context)) *MockReservationHandler_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReservationHandler_Get_Call) Return() *MockReservationHandler_Get_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReservationHandler_Get_Call) RunAndReturn(run func(c *gin.Context)) *MockReservationHandler_Get_Call {
	_c.Run(run)
	return _c
}

// NewMockTestingHandler creates a new instance of MockTestingHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTestingHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTestingHandler {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockTestingHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockTestingHandler is an autogenerated mock type for the testingHandler type
type MockTestingHandler struct {
	mock.Mock
}

type MockTestingHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTestingHandler) EXPECT() *MockTestingHandler_Expecter {
	return &MockTestingHandler_Expecter{mock: &_m.Mock}
}

// Reset provides a mock function for the type MockTestingHandler
func (_mock *MockTestingHandler) Reset(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockTestingHandler_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type MockTestingHandler_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockTestingHandler_Expecter) Reset(c any) *MockTestingHandler_Reset_Call {
	return &MockTestingHandler_Reset_Call{Call: _e.mock.On("Reset", c)}
}

func (_c *MockTestingHandler_Reset_Call) Run(run func(c *gin.Context)) *MockTestingHandler_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTestingHandler_Reset_Call) Return() *MockTestingHandler_Reset_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTestingHandler_Reset_Call) RunAndReturn(run func(c *gin.Context)) *MockTestingHandler_Reset_Call {
	_c.Run(run)
	return _c
}

// Seed provides a mock function for the type MockTestingHandler
func (_mock *MockTestingHandler) Seed(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockTestingHandler_Seed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Seed'
type MockTestingHandler_Seed_Call struct {
	*mock.Call
}

// Seed is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockTestingHandler_Expecter) Seed(c any) *MockTestingHandler_Seed_Call {
	return &MockTestingHandler_Seed_Call{Call: _e.mock.On("Seed", c)}
}

func (_c *MockTestingHandler_Seed_Call) Run(run func(c *gin.Context)) *MockTestingHandler_Seed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTestingHandler_Seed_Call) Return() *MockTestingHandler_Seed_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTestingHandler_Seed_Call) RunAndReturn(run func(c *gin.Context)) *MockTestingHandler_Seed_Call {
	_c.Run(run)
	return _c
}

// NewMockReservationWorker creates a new instance of MockReservationWorker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReservationWorker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReservationWorker {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockReservationWorker{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockReservationWorker is an autogenerated mock type for the reservationWorker type
type MockReservationWorker struct {
	mock.Mock
}

type MockReservationWorker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReservationWorker) EXPECT() *MockReservationWorker_Expecter {
	return &MockReservationWorker_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type MockReservationWorker
func (_mock *MockReservationWorker) Start(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockReservationWorker_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockReservationWorker_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReservationWorker_Expecter) Start(ctx any) *MockReservationWorker_Start_Call {
	return &MockReservationWorker_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockReservationWorker_Start_Call) Run(run func(ctx context.Context)) *MockReservationWorker_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReservationWorker_Start_Call) Return() *MockReservationWorker_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReservationWorker_Start_Call) RunAndReturn(run func(ctx context.Context)) *MockReservationWorker_Start_Call {
	_c.Run(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockStorage is an autogenerated mock type for the storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockStorage
func (_mock *MockStorage) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockStorage_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockStorage_Expecter) Close() *MockStorage_Close_Call {
	return &MockStorage_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockStorage_Close_Call) Run(run func()) *MockStorage_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_Close_Call) Return(err error) *MockStorage_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_Close_Call) RunAndReturn(run func() error) *MockStorage_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Connect provides a mock function for the type MockStorage
func (_mock *MockStorage) Connect() (*sql.DB, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 *sql.DB
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*sql.DB, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *sql.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.DB)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockStorage_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
func (_e *MockStorage_Expecter) Connect() *MockStorage_Connect_Call {
	return &MockStorage_Connect_Call{Call: _e.mock.On("Connect")}
}

func (_c *MockStorage_Connect_Call) Run(run func()) *MockStorage_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_Connect_Call) Return(dB *sql.DB, err error) *MockStorage_Connect_Call {
	_c.Call.Return(dB, err)
	return _c
}

func (_c *MockStorage_Connect_Call) RunAndReturn(run func() (*sql.DB, error)) *MockStorage_Connect_Call {
	_c.Call.Return(run)
	return _c
}
