// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"hotel-booking-api/internal/hotel/model"
	model0 "hotel-booking-api/internal/room/model"
)

// NewMockHotelService creates a new instance of MockHotelService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHotelService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHotelService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockHotelService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockHotelService is an autogenerated mock type for the hotelService type
type MockHotelService struct {
	mock.Mock
}

type MockHotelService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHotelService) EXPECT() *MockHotelService_Expecter {
	return &MockHotelService_Expecter{mock: &_m.Mock}
}

// CreateHotels provides a mock function for the type MockHotelService
func (_mock *MockHotelService) CreateHotels(ctx context.Context, hotels []*model.HotelItem) error {
	ret := _mock.Called(ctx, hotels)

	if len(ret) == 0 {
		panic("no return value specified for CreateHotels")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*model.HotelItem) error); ok {
		r0 = returnFunc(ctx, hotels)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHotelService_CreateHotels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateHotels'
type MockHotelService_CreateHotels_Call struct {
	*mock.Call
}

// CreateHotels is a helper method to define mock.On call
//   - ctx context.Context
//   - hotels []*model.HotelItem
func (_e *MockHotelService_Expecter) CreateHotels(ctx any, hotels any) *MockHotelService_CreateHotels_Call {
	return &MockHotelService_CreateHotels_Call{Call: _e.mock.On("CreateHotels", ctx, hotels)}
}

func (_c *MockHotelService_CreateHotels_Call) Run(run func(ctx context.Context, hotels []*model.HotelItem)) *MockHotelService_CreateHotels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*model.HotelItem
		if args[1] != nil {
			arg1 = args[1].([]*model.HotelItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHotelService_CreateHotels_Call) Return(err error) *MockHotelService_CreateHotels_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHotelService_CreateHotels_Call) RunAndReturn(run func(ctx context.Context, hotels []*model.HotelItem) error) *MockHotelService_CreateHotels_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAllHotels provides a mock function for the type MockHotelService
func (_mock *MockHotelService) RemoveAllHotels(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAllHotels")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHotelService_RemoveAllHotels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAllHotels'
type MockHotelService_RemoveAllHotels_Call struct {
	*mock.Call
}

// RemoveAllHotels is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHotelService_Expecter) RemoveAllHotels(ctx any) *MockHotelService_RemoveAllHotels_Call {
	return &MockHotelService_RemoveAllHotels_Call{Call: _e.mock.On("RemoveAllHotels", ctx)}
}

func (_c *MockHotelService_RemoveAllHotels_Call) Run(run func(ctx context.Context)) *MockHotelService_RemoveAllHotels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHotelService_RemoveAllHotels_Call) Return(err error) *MockHotelService_RemoveAllHotels_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHotelService_RemoveAllHotels_Call) RunAndReturn(run func(ctx context.Context) error) *MockHotelService_RemoveAllHotels_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoomService creates a new instance of MockRoomService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoomService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoomService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRoomService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRoomService is an autogenerated mock type for the roomService type
type MockRoomService struct {
	mock.Mock
}

type MockRoomService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoomService) EXPECT() *MockRoomService_Expecter {
	return &MockRoomService_Expecter{mock: &_m.Mock}
}

// CreateRooms provides a mock function for the type MockRoomService
func (_mock *MockRoomService) CreateRooms(ctx context.Context, rooms []*model0.RoomItem) error {
	ret := _mock.Called(ctx, rooms)

	if len(ret) == 0 {
		panic("no return value specified for CreateRooms")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*model0.RoomItem) error); ok {
		r0 = returnFunc(ctx, rooms)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRoomService_CreateRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRooms'
type MockRoomService_CreateRooms_Call struct {
	*mock.Call
}

// CreateRooms is a helper method to define mock.On call
//   - ctx context.Context
//   - rooms []*model0.RoomItem
func (_e *MockRoomService_Expecter) CreateRooms(ctx any, rooms any) *MockRoomService_CreateRooms_Call {
	return &MockRoomService_CreateRooms_Call{Call: _e.mock.On("CreateRooms", ctx, rooms)}
}

func (_c *MockRoomService_CreateRooms_Call) Run(run func(ctx context.Context, rooms []*model0.RoomItem)) *MockRoomService_CreateRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*model0.RoomItem
		if args[1] != nil {
			arg1 = args[1].([]*model0.RoomItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoomService_CreateRooms_Call) Return(err error) *MockRoomService_CreateRooms_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRoomService_CreateRooms_Call) RunAndReturn(run func(ctx context.Context, rooms []*model0.RoomItem) error) *MockRoomService_CreateRooms_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllRoomTypes provides a mock function for the type MockRoomService
func (_mock *MockRoomService) FindAllRoomTypes(ctx context.Context) ([]*model0.RoomType, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAllRoomTypes")
	}

	var r0 []*model0.RoomType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*model0.RoomType, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*model0.RoomType); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model0.RoomType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoomService_FindAllRoomTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllRoomTypes'
type MockRoomService_FindAllRoomTypes_Call struct {
	*mock.Call
}

// FindAllRoomTypes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoomService_Expecter) FindAllRoomTypes(ctx any) *MockRoomService_FindAllRoomTypes_Call {
	return &MockRoomService_FindAllRoomTypes_Call{Call: _e.mock.On("FindAllRoomTypes", ctx)}
}

func (_c *MockRoomService_FindAllRoomTypes_Call) Run(run func(ctx context.Context)) *MockRoomService_FindAllRoomTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRoomService_FindAllRoomTypes_Call) Return(roomTypes []*model0.RoomType, err error) *MockRoomService_FindAllRoomTypes_Call {
	_c.Call.Return(roomTypes, err)
	return _c
}

func (_c *MockRoomService_FindAllRoomTypes_Call) RunAndReturn(run func(ctx context.Context) ([]*model0.RoomType, error)) *MockRoomService_FindAllRoomTypes_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAllRooms provides a mock function for the type MockRoomService
func (_mock *MockRoomService) RemoveAllRooms(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAllRooms")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRoomService_RemoveAllRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAllRooms'
type MockRoomService_RemoveAllRooms_Call struct {
	*mock.Call
}

// RemoveAllRooms is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoomService_Expecter) RemoveAllRooms(ctx any) *MockRoomService_RemoveAllRooms_Call {
	return &MockRoomService_RemoveAllRooms_Call{Call: _e.mock.On("RemoveAllRooms", ctx)}
}

func (_c *MockRoomService_RemoveAllRooms_Call) Run(run func(ctx context.Context)) *MockRoomService_RemoveAllRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRoomService_RemoveAllRooms_Call) Return(err error) *MockRoomService_RemoveAllRooms_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRoomService_RemoveAllRooms_Call) RunAndReturn(run func(ctx context.Context) error) *MockRoomService_RemoveAllRooms_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReservationService creates a new instance of MockReservationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReservationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReservationService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockReservationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockReservationService is an autogenerated mock type for the reservationService type
type MockReservationService struct {
	mock.Mock
}

type MockReservationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReservationService) EXPECT() *MockReservationService_Expecter {
	return &MockReservationService_Expecter{mock: &_m.Mock}
}

// RemoveAllReservations provides a mock function for the type MockReservationService
func (_mock *MockReservationService) RemoveAllReservations(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAllReservations")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReservationService_RemoveAllReservations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAllReservations'
type MockReservationService_RemoveAllReservations_Call struct {
	*mock.Call
}

// RemoveAllReservations is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReservationService_Expecter) RemoveAllReservations(ctx any) *MockReservationService_RemoveAllReservations_Call {
	return &MockReservationService_RemoveAllReservations_Call{Call: _e.mock.On("RemoveAllReservations", ctx)}
}

func (_c *MockReservationService_RemoveAllReservations_Call) Run(run func(ctx context.Context)) *MockReservationService_RemoveAllReservations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReservationService_RemoveAllReservations_Call) Return(err error) *MockReservationService_RemoveAllReservations_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReservationService_RemoveAllReservations_Call) RunAndReturn(run func(ctx context.Context) error) *MockReservationService_RemoveAllReservations_Call {
	_c.Call.Return(run)
	return _c
}
